### ISSUE TITLE
Many error emails overnight about unreachable domains

### ISSUE THREAD

**Issue by konklone** [SSLMate/sslmate#15]
I got 9 individual emails from SSLMate last night, at 5:31am (after daylight savings change) that each said my domain was unreachable.

This is SSLMate's free domain watching service. It includes domains whose certificate was not purchased through SSLMate.

**Comment by tollmanz** [comment]
I too received an alert, but only a single one. I believe the alert to be erroneous.

> The SSLMate Certificate Expiration Checker has been unable to contact
{domain.com}:443 for the last 3 days.
>
> We'll keep trying, but unless we can successfully connect, we can't
check its SSL certificate for expiration.

**Comment by AGWA** [comment]
Indeed, the alerts were erroneous.  Sorry about the noise.  Basically, SSLMate has been running on a backup server for the last three days because of maintenance by our hosting provider, and the expiration checker wasn't properly failed over.  I'll be moving SSLMate back to the primary server later today and resetting the expiration checker state.  I'm also going to add a safety valve that raises an alarm if >10% of hosts are found to be unreachable.
