### ISSUE TITLE
Supporting OCSP stapling

### ISSUE THREAD

**Issue by konklone** [SSLMate/sslmate#18]
I've found the online resources around OCSP stapling very disappointing, in terms of explaining the mechanics of web server configuration. 

As [best as I can tell](https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx), in nginx and Apache, they both want you to point the `ssl_trusted_certificate` or `SSLCACertificateFile` at a bundle including the *root* and *intermediate* certificates, in order to retrieve a staple-ready response to vouch for the client certificate. I can make inferences as to why that's the case, and how OCSP checks work, but I admit I don't really get it, and I rely basically entirely on SSL Labs to verify that it's turned on correctly.

In any case, SSLMate deposits the client cert, the key, a chain of client + intermediates, and a chain of just intermediates, for various nginx/Apache use cases. None of those include the root, and so I can't point the `ssl_trusted_certificate` or `SSLCACertificateFile` values at them.

Would SSLMate consider adding a 5th file to its output? Something like `domain.com.trusted.crt`, or `domain.com.upstream.crt` or something? Or other ideas to ease the enabling of OCSP stapling?

**Comment by tovare** [comment]
:+1: I agree, it would have been great if SSLMate provided instructions for OSCP stapling, and tool support to easily get the required files. I understand that OSCP isn´t perfect and under revision, but I´d love anything that could shave off a few milliseconds setting up a connection ... and OSCP is the only thing left on my list of things to try

**Comment by AGWA** [comment]
I hope to investigate OCSP stapling in depth this week.  I really want to get to the bottom of the root certificate requirement - information about it is vague and conflicting, and I would like to avoid providing the root if it's not necessary.

**Comment by AGWA** [comment]
After testing both Apache and nginx, and taking some deep dives into their source code (and OpenSSL's), I have determined that the root certificate is only necessary if the server validates the OCSP response.  Apache does not validate the response, so the root is never necessary with Apache.  Nginx only validates the response if the `ssl_stapling_verify` option is enabled.

I think that, until OCSP Must-Staple happens, validating the OCSP response has little value and should just be disabled to reduce configuration overhead.  The client validates the OCSP response anyways, so even if an active attacker induced your server to staple a bogus response, the client would just ignore it and it would be no different from not having stapling.

Without further ado, here is the configuration I recommend (which should be combined with the config already recommended by `sslmate mkconfig`):

### nginx

    ssl_stapling on;
    ssl_stapling_verify off;

Some guides recommend you configure a DNS server using the `resolver` option.  If you don't, the hostname in the OCSP URL is resolved once, when nginx starts, using the system's resolver, and is never resolved again.  This would cause OCSP stapling to stop working if the OCSP responder ever changed IP address.  The problem is, to use `resolver`, you have to specify the IP address of some DNS resolver, which is really silly when your system already has a DNS server configured, possibly obtained via DHCP.  I'm not sure what to recommend for this, but if you're comfortable relying on Google's Public DNS, then you can add this to your config:

    resolver 8.8.8.8;

One quirk with nginx is that it performs stapling on-demand but asynchronously, meaning the first SSL connection handled by a worker process never has a stapled response.  This makes testing really frustrating - you may have to make several requests (up to the number of worker processes) before you see a stapled response.

### Apache

Inside the virtual host, add:

    SSLUseStapling on
    SSLStaplingReturnResponderErrors off
    SSLStaplingResponderTimeout 5

In the global configuration (not a VirtualHost), you need to configure the `SSLStaplingCache` parameter.  On Debian/Ubuntu, I recommend putting the following in `/etc/apache2/mods-enabled/ssl.conf`:

    SSLStaplingCache shmcb:${APACHE_RUN_DIR}/ssl_stapling_cache(128000)

On other distros, I'm not sure if `${APACHE_RUN_DIR}` is defined.  It should be a temporary/runtime-ish directory only writable by root (I don't recommend using `/tmp`, as the DigitalOcean guide does).  Unfortunately, this makes it difficult to provide a good, cross-distro guide for OCSP stapling with Apache.

**Comment by tovare** [comment]
Thank you for investigating this.

**Comment by konklone** [comment]
This is the most helpful thing I've ever read about OCSP stapling on Apache and nginx. Thank you for diving in!

> After testing both Apache and nginx, and taking some deep dives into their source code (and OpenSSL's), I have determined that the root certificate is only necessary if the server validates the OCSP response.

So does this mean that on nginx, I should provide an `ssl_trusted_certificate` of the `.chained.crt` file?

On Apache, do I need to specify a `SSLCACertificateFile` directive, and if so what should it be?

If you turned your comment above, and the answers to my questions, into a small blog post, it'd probably become as "canonical" as Digital Ocean's pretty quickly.

**Comment by AGWA** [comment]
No, you don't need to specify `ssl_trusted_certificate` (assuming `ssl_stapling_verify` is off) or `SSLCACertificateFile`.  Just configure the certificate the normal way (e.g. `ssl_certificate /path/to/chained.crt`), and then add the options I gave in my comment above.

I am indeed going to write a blog post based on this.

**Comment by konklone** [comment]
Got it. That made everything click, I get what the trusted cert was for and
why it's not needed. Thanks for cutting through the confusion.

**Comment by xxdesmus** [comment]
Still running into trouble here. Works fine in the browser, curl complains 

http://certificate.revocationcheck.com/canhazip.com

GET and POST are both returning "Error parsing OCSP response"

My nginx config:

```
        ssl on;

        # SSLMate Comodo cert
        ssl_certificate /path/to/www.canhazip.com.chained.crt;
        ssl_certificate_key  /path/to/www.canhazip.com.key;

        ssl_prefer_server_ciphers on;
        ssl_protocols   TLSv1 TLSv1.1 TLSv1.2;

        ## CF origin pull cert
        ssl_client_certificate /path/to/origin-pull.pem;
        ssl_verify_client on;

        ## End of life IE
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!3DES:!DES:!MD5:!PSK:!RC4:!RSA;

        ## SSL session caching
        ssl_session_cache       builtin:1000  shared:SSL:20m;
        ssl_session_timeout     4h;
        ssl_buffer_size 1400;
        ssl_session_tickets on;

        ## SPDY header compression
        spdy_headers_comp 9;

        ## OCSP stapling
        ssl_stapling            on;
        ssl_stapling_verify     off;
        resolver 8.8.8.8 valid=300s;
        resolver_timeout 10s;
```

Am I doing something dumb?

**Comment by AGWA** [comment]
@xxdesmus  Could you paste the exact curl command and response that you get?  Your config looks correct, and both `openssl s_client` and SSL Labs show that OCSP stapling is working, so I can't think of what this could be besides a curl problem.

**Comment by xxdesmus** [comment]
```
curl -v4 https://canhazip.com
* Rebuilt URL to: https://canhazip.com/
* Hostname was NOT found in DNS cache
*   Trying 104.20.20.43...
* Connected to canhazip.com (104.20.20.43) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

```
curl --version
curl 7.37.1 (x86_64-pc-linux-gnu) libcurl/7.37.1 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by AGWA** [comment]
@xxdesmus This is an issue unrelated to OCSP stapling: you're missing the last certificate in the certificate chain, according to `openssl s_client`:

```
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=www.canhazip.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
```

There should be a third certificate:
```
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
```

`www.canhazip.com.chained.crt` *should* contain the third cert. Could you run `sslmate download www.canhazip.com` to re-download it, in case the file got corrupted somehow?

**Comment by xxdesmus** [comment]
I think I know what the issue is. Let me tet something and get back to you. 99% sure it's not at all related to sslmate though.

**Comment by xxdesmus** [comment]
Fixed. It was an issue on CloudFlare's side. 

I spoke with our security team (I work at CloudFlare), and the reason this 3rd cert was stripped out when I uploaded it was because

"That third cert "COMODO RSA Certification Authority" is trusted by all browsers, but not curl."  ...that's what caused the issue here.

In the interim I used our "Custom (provide certificate chain)" option and it's working now:

```
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=www.canhazip.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
```

We will get this fixed on our side of things. Sorry for the false alarm.

**Comment by AGWA** [comment]
> That third cert "COMODO RSA Certification Authority" is trusted by all browsers

That's not remotely true.  For instance, it was [only added to Firefox late last year](https://bugzilla.mozilla.org/show_bug.cgi?id=1062589), and it's not in Firefox 31, which is an ESR release that's still supported.  It's also not in the root store on Debian Jessie (probably recent Ubuntu releases as well), [OS X Yosemite](https://support.apple.com/en-us/HT202858), or [iOS 8](https://support.apple.com/en-us/HT204132).  (And note that Chrome uses the OS's root store.)  Not to mention the people running out-of-date OSes/browsers...

CloudFlare should be serving the longer chain - yes, this has overhead, but the price to pay for the shorter chain is too high.

**Comment by AGWA** [comment]
In case you missed it, I published a blog post about OCSP stapling a while back: https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx

One thing that changed between this GitHub discussion and the blog post is that I decided to turn on OCSP response verification in nginx.  I did this because browsers are becoming stricter with stapled OCSP responses.  Firefox now hard fails on bogus stapled responses, and Chrome is planning to do the same.  Be aware that prior to nginx 1.9.2, nginx could sometimes return an expired response even if verification was enabled, and also that Apache doesn't support verification of OCSP response signatures at all (although it does check things like expiration).

Apache's lack of signature verification is not great -- OCSP responders are notoriously flaky, so the more checking the better.  That said, all the OCSP responder failures I've seen have been serving no response or serving an expired response, and I think serving an otherwise valid response with a bogus signature would be a pretty strange failure mode.  There's also the risk of an active attacker DoSing your website by feeding your server a bogus OCSP response (OCSP uses HTTP, not HTTPS), but that would be a pretty strange way to DoS someone, and could be caught and quickly addressed by monitoring.

**Comment by tovare** [comment]
Tanks a lot. I´m now at A+ :-)

https://www.ssllabs.com/ssltest/analyze.html?d=tovare.com

(I gut a bit surprised when doing the config, because I got a B in the
test, but it wasn´t related. After generating dhparams.pem and doing some
additional config, I was fine)



2015-07-08 4:31 GMT+02:00 Andrew Ayer <notifications@github.com>:
